### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by jrmetzge** [jrmetzge/to_RStudio#1]
# First Issue

## Second Heading

Linking to Lauren's [Jake.md](https://github.com/lauren-bell-ak/github_clinic/blob/main/users/Jacob.md)

**Comment by jrmetzge** [comment]
I think you you use na. omit [here] (https://github.com/jrmetzge/to_RStudio/blob/5829738baf70dd622fa864303def8eb54ab4419d/plampengs_flipper_vs_bodymass.R#L9)

**Comment by bjaywalk** [comment]
All figured out!
